# 이 파일은 애플리케이션의 엔트리 포인트 역할을 합니다. 공통 설정과 어떤 프로파일을 활성화할지 결정합니다.

spring:
  profiles:
    active: "dev" # 기본값으로 dev 활성화 (CLI 인자로 변경 가능)

  main:
    banner-mode: console

server:
  port: 8888

# 공통 비즈니스 로직에 쓰이는 값
my:
  secret: ${random.value}
  uuid: ${random.uuid}
  long: ${random.long}

# Actuator 기본 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: "health,info,startup"
  endpoint:
    startup:
      enabled: true
    health:
      probes:
        enabled: true