spring:
  config:
    import: 
      - "optional:classpath:db-config.yml"

server:
  tomcat:
    threads:
      max: 200

management:
  endpoint:
    health:
      show-details: when_authorized # 보안을 위해 인증된 사용자만 상세 정보 확인

mail:
  host: smtp.real-server.com
  port: 465
  auth-enabled: true
  # 실제 비밀번호는 여기서 적지 않고 ./config/application.yml에서 작성하거나 주입받음