# 이 파일은 애플리케이션의 엔트리 포인트 역할을 합니다. 공통 설정과 어떤 프로파일을 활성화할지 결정합니다.

spring:
  profiles: # 커맨드 라인 인자가 application.yml 파일보다 우선순위가 높습니다. 따라서 파일에 dev라고 적혀 있어도, 서버 실행 시 --spring.profiles.active=prod를 주면 prod가 활성화됩니다.
    default: "dev"
    # include:
    # - "common"
    # - "prod"
  config:
    import:  # 모듈 임포트
      - "optional:classpath:config/db-config.yml"
      - "optional:classpath:config/api-config.yml"
      - "optional:classpath:config/batch-config.yml"
  main:
    banner-mode: console

# 공통 비즈니스 로직에 쓰이는 값
my:
  secret: ${random.value}
  uuid: ${random.uuid}
  long: ${random.long}

# Actuator 기본 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: "health,info,startup"
  endpoint:
    startup:
      enabled: true
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: "prod"
  banner:
    location: "classpath:banners/banner-prod.txt"
server:
  tomcat:
    threads:
      max: 200
  port: 9090

management:
  endpoint:
    health:
      show-details: when_authorized # 보안을 위해 인증된 사용자만 상세 정보 확인

logging:
  level:
    root: WARN # 운영은 중요한 경고/에러만 남김
    # com.yourpackage.app: INFO # 우리 팀 코드는 INFO까지

---
spring:
  config:
    activate:
      on-profile: "dev"
  banner:
    location: "classpath:banners/banner-dev.txt"

debug: true

server:
  port: 9999

management:
  endpoint:
    health:
      show-details: always

# logging:
#   level:
#     root: DEBUG # 개발 시에는 SQL 쿼리나 상세 흐름을 보기 위해 DEBUG
#     # org.springframework: INFO # 스프링 프레임워크 로그는 너무 많으니 INFO로 조절